(
 ((name . "👉😎👉") (aliases "zoop" "fingerguns"))
 ((name . "¯\\_(ツ)_/¯") (aliases "shrug"))
 ((name . "(╯°□°）╯︵ ┻━┻") (aliases "tableflip"))
 ((name . "┬──┬ ノ( ゜-゜ノ)") (aliases "unflip"))
 ((name . "🎈") (aliases "balloon" "yay"))
 ((name . "™️") (aliases "tm" "trademark"))
 ((name . "👉🤠👉") (aliases "cowboy" "shipit"))
 ((name . "https://whereby.com/cmoesgaard") (aliases "whereby" "cmoesgaard"))
 ((name . "👉👴👉") (aliases "oldman"))
 ((name . "✨🇪​🇩​🇧✨") (aliases "edb"))
)
